name: build-exes

on:
  workflow_dispatch:

jobs:
  build-executables:
    strategy:
      fail-fast: false
      matrix:
        #os: [windows-2019, ubuntu-18.04, macos-10.15]
        os: [ubuntu-18.04]
        include:
          # - os: windows-2019
          #   executable_ext: .exe
          #   executable_os: win
          - os: ubuntu-18.04
            executable_ext: ""
            executable_os: linux
          # - os: macos-10.15
          #   executable_ext: ""
          #   executable_os: macos

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # get all history and tags

      - uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: venv-${{ matrix.os }}-${{ hashFiles('**/poetry.lock') }}

      - name: Install poetry
        run: python -m pip install poetry==1.1.11

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Install dependencies
        run: poetry install

      - name: Get exectuable version name
        run: |
          vers=$(git describe --tags)
          echo "vers is: $vers"
          echo "vers=$vers" >> $GITHUB_ENV

      - name: Build with pyinstaller for ${{matrix.executable_os}}
        run: poetry run pyinstaller hpcflow/cli.py --name=hpcflow-${{ env.vers }} --onefile

      - name: Rename executable for ${{matrix.executable_os}}
        run: mv dist/hpcflow-${{ env.vers }}${{ matrix.executable_ext }} dist/hpcflow-${{ env.vers }}-${{ matrix.executable_os }}${{ matrix.executable_ext }}

      - uses: actions/upload-artifact@v2
        with:
          name: hpcflow-${{ env.vers }}-${{ matrix.executable_os }}${{ matrix.executable_ext }}
          path: dist/hpcflow-${{ env.vers }}-${{ matrix.executable_os }}${{ matrix.executable_ext }}

      - name: Basic executable test
        run: dist/hpcflow-${{ env.vers }}-${{ matrix.executable_os }}${{ matrix.executable_ext }} --version

  build-executables-CentOS:
    runs-on: ubuntu-latest
    needs: bump-version
    container:
      image: aplowman/centos7-poetry
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.base.ref }} # otherwise we get the ref when the workflow started (missing above commit)

      - name: Configure poetry
        run: poetry config virtualenvs.in-project true

      - name: Cache the virtualenv
        uses: actions/cache@v2
        with:
          path: ./.venv
          key: venv-CentOS-${{ hashFiles('**/poetry.lock') }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Build with pyinstaller for ${{matrix.executable_os}}
        run: poetry run pyinstaller hpcflow/cli.py --name=hpcflow-${{ env.vers }}-CentOS --onefile

      - uses: actions/upload-artifact@v2
        with:
          name: hpcflow-${{ env.vers }}-CentOS
          path: dist/hpcflow-${{ env.vers }}-CentOS

      - name: Basic executable test
        run: dist/hpcflow-${{ env.vers }}-CentOS --version
