name: Bump downstream project version
concurrency: bump-downstream

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["release"]
    types:
      - completed

env:
  PYTHON_VERSION_MAKE_PRs: "3.13"
  POETRY_VERSION: "2.1.3"

jobs:
  create-matflow-pull-request:
    if: ( github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' )
    runs-on: ubuntu-latest
    steps:
      - name: Checkout MatFlow develop branch
        uses: actions/checkout@v7
        with:
          repository: hpcflow/matflow
          fetch-depth: 0 # get all history and tags
          token: ${{ secrets.HPCFLOW_ACTIONS_TOKEN }}
          ref: develop

      - name: Configure git
        uses: hpcflow/github-support/configure-git@main

      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION_MAKE_PRs }}

      - name: Setup poetry
        uses: hpcflow/github-support/setup-poetry@main
        with:
          version: ${{ env.POETRY_VERSION }}

      - name: Install dependencies
        run: |
          poetry install

      - name: Checkout branch
        run: |
          git switch bump/hpcflow 2>/dev/null || git switch -c bump/hpcflow
          git merge develop

      - name: Get version number
        id: get_version
        run: |
          HPCFLOW_VERSION=$(poetry add hpcflow@latest --dry-run --allow-prereleases | head -n 1 | sed -E 's/.*\^([0-9a-z.]+).*/\1/')
          echo "HPCFLOW_VERSION=${HPCFLOW_VERSION}" >> "$GITHUB_OUTPUT"

      - name: Update hpcflow
        env:
          HPCFLOW_VERSION: ${{ steps.get_version.outputs.HPCFLOW_VERSION }}
        run: poetry add hpcflow@${HPCFLOW_VERSION}

      - name: Commit changes
        run: |
          git add pyproject.toml poetry.lock
          git commit -m"feat: bump hpcflow version"
          git push --set-upstream origin bump/hpcflow

      - name: Create pull request
        run: gh pr create -B develop -H bump/hpcflow --title 'Bump hpcflow version' --body 'Created by Github action'
        env:
          GITHUB_TOKEN: ${{ secrets.HPCFLOW_ACTIONS_TOKEN }}
