name: Generate test programs
env:
  PYTHON_VERSION: "3.13"
  POETRY_VERSION: "1.4"
on:
  workflow_dispatch:

jobs:
  windows:
    name: Build Windows Executables
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
      - name: Set up python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v7
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Cache dependencies
        uses: hpcflow/github-support/init-cache@main
        with:
          name: make-test-programs
          version: ${{ env.PYTHON_VERSION }}
      - name: Set up poetry
        uses: hpcflow/github-support/setup-poetry@main
        with:
          version: ${{ env.POETRY_VERSION }}
      - name: Install dependencies
        run: poetry install --without dev
      - name: Build `hello_world.py` with pyinstaller for Windows
        working-directory: hpcflow/data/programs/hello_world
        run: poetry run pyinstaller --distpath ./dist/onefile --onefile --clean -y hello_world.py
      - name: Upload executable artifact
        id: upload-file
        uses: actions/upload-artifact@v7
        with:
          name: hello_world.exe
          path: hpcflow/data/programs/hello_world/dist/onefile/hello_world.exe
